//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Calc.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="CalcParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface ICalcListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="CalcParser.prog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProg([NotNull] CalcParser.ProgContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CalcParser.prog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProg([NotNull] CalcParser.ProgContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CalcParser.assign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssign([NotNull] CalcParser.AssignContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CalcParser.assign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssign([NotNull] CalcParser.AssignContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CalcParser.ifstatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfstatement([NotNull] CalcParser.IfstatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CalcParser.ifstatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfstatement([NotNull] CalcParser.IfstatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CalcParser.elsestatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElsestatement([NotNull] CalcParser.ElsestatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CalcParser.elsestatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElsestatement([NotNull] CalcParser.ElsestatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CalcParser.whilestatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhilestatement([NotNull] CalcParser.WhilestatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CalcParser.whilestatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhilestatement([NotNull] CalcParser.WhilestatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CalcParser.forstatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForstatement([NotNull] CalcParser.ForstatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CalcParser.forstatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForstatement([NotNull] CalcParser.ForstatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CalcParser.boolexpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBoolexpr([NotNull] CalcParser.BoolexprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CalcParser.boolexpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBoolexpr([NotNull] CalcParser.BoolexprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CalcParser.mathexpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMathexpr([NotNull] CalcParser.MathexprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CalcParser.mathexpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMathexpr([NotNull] CalcParser.MathexprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CalcParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValue([NotNull] CalcParser.ValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CalcParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValue([NotNull] CalcParser.ValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CalcParser.id"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterId([NotNull] CalcParser.IdContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CalcParser.id"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitId([NotNull] CalcParser.IdContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CalcParser.varid"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarid([NotNull] CalcParser.VaridContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CalcParser.varid"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarid([NotNull] CalcParser.VaridContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CalcParser.memberid"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMemberid([NotNull] CalcParser.MemberidContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CalcParser.memberid"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMemberid([NotNull] CalcParser.MemberidContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CalcParser.mathfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMathfunc([NotNull] CalcParser.MathfuncContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CalcParser.mathfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMathfunc([NotNull] CalcParser.MathfuncContext context);
}
