//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Calc.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="CalcParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface ICalcVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="CalcParser.prog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProg([NotNull] CalcParser.ProgContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CalcParser.assign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssign([NotNull] CalcParser.AssignContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CalcParser.ifstatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfstatement([NotNull] CalcParser.IfstatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CalcParser.elsestatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElsestatement([NotNull] CalcParser.ElsestatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CalcParser.whilestatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhilestatement([NotNull] CalcParser.WhilestatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CalcParser.forstatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForstatement([NotNull] CalcParser.ForstatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CalcParser.boolexpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBoolexpr([NotNull] CalcParser.BoolexprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CalcParser.mathexpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMathexpr([NotNull] CalcParser.MathexprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CalcParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValue([NotNull] CalcParser.ValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CalcParser.id"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitId([NotNull] CalcParser.IdContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CalcParser.varid"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarid([NotNull] CalcParser.VaridContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CalcParser.memberid"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMemberid([NotNull] CalcParser.MemberidContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CalcParser.mathfunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMathfunc([NotNull] CalcParser.MathfuncContext context);
}
